# Generated by Django 4.1.5 on 2023-02-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_db_pub_date_task_db_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_db',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='task_db',
            name='user',
            field=models.CharField(default='noname', max_length=55, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
