# Generated by Django 3.2.12 on 2023-02-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_db_options_task_db_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_db',
            name='user',
            field=models.CharField(default='NoName', max_length=55, verbose_name='Имя'),
        ),
    ]
